# Generated by Django 4.2 on 2023-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_orderhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ManyToManyField(to='main.product', verbose_name='Продукт'),
        ),
    ]
